"""followers

Revision ID: 64db7c49a286
Revises: b2f3cef8ea98
Create Date: 2019-11-08 09:42:44.139236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64db7c49a286'
down_revision = 'b2f3cef8ea98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
